<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>com.l2jfree</groupId>
		<artifactId>l2jfree-module</artifactId>
		<version>1.5.1</version>
		<relativePath>../l2jfree-module</relativePath>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>l2jfree-scripting-engines</artifactId>
	<name>${project.artifactId}-${project.version}</name>
	<packaging>jar</packaging>
	<dependencies>
		<dependency>
			<groupId>org.eclipse.jdt</groupId>
			<artifactId>ecj</artifactId>
			<version>3.44.0</version>
		</dependency>
		<dependency>
			<groupId>org.python</groupId>
			<artifactId>jython</artifactId>
			<version>${jython.version}</version>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>graalpy-experiment</id>
			<dependencies>
				<dependency>
					<groupId>org.graalvm.polyglot</groupId>
					<artifactId>polyglot</artifactId>
					<version>${graalpy.version}</version>
					<scope>test</scope>
				</dependency>
				<dependency>
					<groupId>org.graalvm.polyglot</groupId>
					<artifactId>python</artifactId>
					<version>${graalpy.version}</version>
					<type>pom</type>
					<scope>test</scope>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>build-helper-maven-plugin</artifactId>
						<version>3.6.1</version>
						<executions>
							<execution>
								<id>add-graalpy-experiment-tests</id>
								<phase>generate-test-sources</phase>
								<goals>
									<goal>add-test-source</goal>
								</goals>
								<configuration>
									<sources>
										<source>${project.basedir}/src/graalpy-test/java</source>
									</sources>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<build>
		<defaultGoal>install</defaultGoal>
		<plugins>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
	
