<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>com.l2jfree</groupId>
		<artifactId>l2jfree-module</artifactId>
		<version>1.4.0</version>
		<relativePath>../l2jfree-module</relativePath>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>l2jfree-login</artifactId>
	<name>${project.artifactId}-${project.version}</name>
	<packaging>jar</packaging>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.l2jfree</groupId>
			<artifactId>l2j-commons</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.l2jfree</groupId>
			<artifactId>l2j-mmocore</artifactId>
			<version>${project.version}</version>
		</dependency>
		<!-- Updating dependencies below is strongly NOT recommend. -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-mock</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate</artifactId>
			<version>3.2.2.ga</version>
		</dependency>
		<dependency>
			<groupId>javax.transaction</groupId>
			<artifactId>jta</artifactId>
			<version>1.1</version>
		</dependency>
	</dependencies>
	<build>
		<defaultGoal>package</defaultGoal>
		<testResources>
			<testResource>
				<directory>config</directory>
			</testResource>
		</testResources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
